# normal
# color0 #202020
# color1 #dd241d
# color2 #98a71a
# color3 #c76921
# color4 #456588
# color5 #d16286
# color6 #58ad8a
# color7 #989898

# # bright
# color8 #737373
# color9 #ff4934
# color10 #b8db36
# color11 #ea7d2f
# color12 #8385a8
# color13 #f3869b
# color14 #7ec09c
# color15 #ebebeb

gui:
  showIcons: true
  showBottomLine: false
  scrollHeight: 10
  mouseEvents: false
  mainPanelSplitMode: horizontal
  commandLogSize: 8
  theme:
    activeBorderColor:
      - "#98a71a"
      - bold
    inactiveBorderColor:
      - "#989898"
    selectedLineBgColor:
      - default
      - bold
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - "#7ec09c"
    cherryPickedCommitFgColor:
      - "#202020"
      - bold
    unstageChangesColor:
      - "#c76921"
  branchColors:
    'feature': "#456588"
    'issue': "#456588"
    'master': "#b8db36"
  authorColors:
    'Lim Chun Leng': "#456588"
    'ChunLeng Lim': "#456588"
    '*': "#989898"
keybinding:
  universal:
    remove: 'x'
    optionMenu: '?'
