# normal
# color0 #202020
# color1 #ff141d
# color2 #6d9c10
# color3 #bfbf31
# color4 #3a5aa3
# color5 #d182d6
# color6 #28869c
# color7 #737373

# bright
# color8 #939393
# color9 #ff7964
# color10 #68c336
# color11 #cccc7f
# color12 #6f95d8
# color13 #f3b6fb
# color14 #4ea9cc
# color15 #d0d0d0

gui:
  showIcons: true
  showBottomLine: false
  scrollHeight: 10
  mouseEvents: false
  mainPanelSplitMode: horizontal
  commandLogSize: 8
  theme:
    activeBorderColor:
      - "#6d9c10"
      - bold
    inactiveBorderColor:
      - "#737373"
    selectedLineBgColor:
      - default
      - bold
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - "#28869c"
    cherryPickedCommitFgColor:
      - "#202020"
      - bold
    unstageChangesColor:
      - "#ff7964"
  branchColors:
    'feature': "#3a5aa3"
    'issue': "#3a5aa3"
    'master': "#bfbf31"
  authorColors:
    'Lim Chun Leng': "#3a5aa3"
    'ChunLeng Lim': "#3a5aa3"
    '*': "#737373"
keybinding:
  universal:
    remove: 'x'
    optionMenu: '?'
  commits:
    # squashDown and markCommitAsFixup are often mispressed because they are undercase of the commonly used 'S' and 'F'
    # key. assign random to the unused keys so that they won't be accidentally activated
    squashDown: '<c-v>'
    markCommitAsFixup: '<c-2>'

